name: Deploy to FTP server

on:
  push:
    branches:
      - main   # Trigger this action when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via FTP
      uses: samkirkland/ftp-deploy-action@v4.3.6
      with:
        server: ${{ secrets.FTP_SERVER }}     # Use 'server' instead of 'ftp-server'
        username: ${{ secrets.FTP_USERNAME }} # Use 'username' instead of 'ftp-username'
        password: ${{ secrets.FTP_PASSWORD }} # Use 'password' instead of 'ftp-password'
        local-dir: ./                         # This is the directory of your project that you want to upload
        server-dir: /modules/addons/addons-care/  # The target directory on your server
